### ISSUE TITLE
Project Window Asset Creation in wrong folder if a folder is selected.

### ISSUE THREAD

**Issue by JasonJonesLASM** [LifeandStyleMedia/UAlive#51]

**Comment by JasonJonesLASM** [comment]
Fixed

**Comment by jrDev1** [comment]
This is not fixed, it still creates files outside of selected folder.

Thanks,
jrDev

**Comment by JasonJonesLASM** [comment]
Please show some way of reproducing this with an image/gif. I've changed it and tested selecting the folder, creates it inside the selected folder, selected folder and object, creates it inside folder of selected Object, and just an object selected. All went exactly where I would expect them to.

**Comment by jrDev1** [comment]
![UAlive Asset Issue2](https://user-images.githubusercontent.com/16272193/93382445-21f45200-f830-11ea-8a9a-302c1491b379.gif)
